name: Deploy Supabase Edge Functions

on:
  push:
    branches: [main]

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Deploy functions
        run: supabase functions deploy enrich-wish
        env:
          SUPABASE_ACCESS_TOKEN: ${{ vars.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
